### ISSUE TITLE
Don't let Troika double import THREE

### ISSUE THREAD

**Issue by Atlinx** [RutgersGRID/lambertvillexr#22]
Tried replacing THREE with AFRAME.THREE, but hitting error:

```
aframe-troika-text.js:7288 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Color')
    at aframe-troika-text.js:7288:45
    at aframe-troika-text.js:9275:3
```

This is relevant to the `feat/_use-troika-text` branch.

**Comment by Atlinx** [comment]
Fixed in latest version of troika branch (67abf06)
